now actions require clang-format and clang-tidy

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -19,7 +19,7 @@ jobs:
       run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
     - name: Install standard library headers for clang and clang tools
       run: sudo apt install clang-tidy-18 clang-format-18 clang-tidy clang-format libc++-18-dev
-    - name: INstall the newest ninja
+    - name: Install the newest ninja
       run: sudo wget -qO /usr/local/bin/ninja.gz https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip && sudo gunzip /usr/local/bin/ninja.gz && sudo chmod a+x /usr/local/bin/ninja
     - uses: actions/setup-python@v5
       with:
@@ -28,15 +28,27 @@ jobs:
       run: pip install pre-commit cpplint && pre-commit install && pre-commit autoupdate --bleeding-edge
     - name: Build project
       run: ./scripts/make_debug.sh
-    - name: Run pre-commit on changed files
+    - name: Run clang-format on all module files
       run: |
-        if find . -iname '*.cxx' -o -iname '*.ixx' | xargs clang-tidy-18 --extra-arg=-stdlib=libc++ -p build/debug/ -header-filter=.*; then  
-          echo "pre-commit-result=0" >>  $GITHUB_OUTPUT 
+        if find . -iname '*.cxx' -o -iname '*.ixx' | xargs clang-format-18; then  
+          echo "clang-format-result=0" >>  $GITHUB_OUTPUT 
         else 
-          echo "pre-commit-result=1" >>  $GITHUB_OUTPUT 
+          echo "clang-format-result=1" >>  $GITHUB_OUTPUT 
         fi;
       shell: bash
-      id: run_pre_commit
-    - name: Pre-commit check
-      if: steps.run_pre_commit.outputs.pre-commit-result > 0
-      run: exit 1
+      id: run_clang_format
+    - name: Run clang-tidy on all module files
+      run: |
+        if find . -iname '*.cxx' -o -iname '*.ixx' | xargs clang-tidy-18 --extra-arg=-stdlib=libc++ -p build/debug/ -header-filter=.*; then  
+          echo "clang-tidy-result=0" >>  $GITHUB_OUTPUT 
+        else 
+          echo "clang-tidy-result=1" >>  $GITHUB_OUTPUT 
+        fi;
+      shell: bash
+      id: run_clang_tidy
+    - name: clang-format check
+      if: steps.run_clang_format.outputs.clang-format-result > 0
+      run: echo "Some of your c++ files are not formatted according to the .clang-format file" && exit 1
+    - name: clang-tidy check
+      if: steps.run_clang_tidy.outputs.clang-tidy-result > 0
+      run: echo "You failed to fulfill some of requirements posed in the .clang-tidy file" && exit 1
